-- MySQL Script generated by MySQL Workbench
-- 2018年11月05日 星期一 15时59分22秒
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema upsite
-- -----------------------------------------------------
-- 网站升级

-- -----------------------------------------------------
-- Schema upsite
--
-- 网站升级
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `upsite` DEFAULT CHARACTER SET utf8mb4 ;
USE `upsite` ;

-- -----------------------------------------------------
-- Table `upsite`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `upsite`.`admin` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `nickName` VARCHAR(20) NOT NULL,
  `pwd` CHAR(32) NOT NULL,
  `token` CHAR(32) NOT NULL DEFAULT '' COMMENT '长时间缓存的token',
  `time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `upsite`.`opraLog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `upsite`.`opraLog` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `uid` INT(10) UNSIGNED NOT NULL,
  `type` TINYINT(3) UNSIGNED NOT NULL COMMENT '0管理员 1用户',
  `msg` TINYTEXT NULL DEFAULT NULL,
  `time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
COMMENT = '管理员操作记录';


-- -----------------------------------------------------
-- Table `upsite`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `upsite`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(40) NOT NULL,
  `nickName` VARCHAR(20) NOT NULL,
  `pwd` CHAR(32) NOT NULL,
  `token` CHAR(32) NOT NULL DEFAULT '' COMMENT '长时间缓存的token',
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `parent` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '所属帐号',
  `time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `tel` CHAR(11) NOT NULL DEFAULT '',
  `contact` VARCHAR(10) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `upsite`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `upsite`.`company` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(40) NOT NULL DEFAULT '',
  `contact` VARCHAR(10) NULL DEFAULT '',
  `tel` CHAR(11) NOT NULL DEFAULT '',
  `belong` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_company_1_idx` (`belong` ASC),
  CONSTRAINT `fk_company_1`
    FOREIGN KEY (`belong`)
    REFERENCES `upsite`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = '标签：单位';


-- -----------------------------------------------------
-- Table `upsite`.`site`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `upsite`.`site` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `v4url` TINYTEXT NOT NULL,
  `v6url` TINYTEXT NOT NULL COMMENT '不含http前缀',
  `belong` INT UNSIGNED NOT NULL,
  `company` INT UNSIGNED NULL DEFAULT NULL COMMENT '所属单位',
  `isHttps` TINYINT NOT NULL DEFAULT 0,
  `isBoth` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否是https+http',
  `cert` JSON NULL DEFAULT NULL,
  `time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_site_2_idx` (`company` ASC),
  INDEX `fk_site_1_idx` (`belong` ASC),
  CONSTRAINT `fk_site_1`
    FOREIGN KEY (`belong`)
    REFERENCES `upsite`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_site_2`
    FOREIGN KEY (`company`)
    REFERENCES `upsite`.`company` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = '网站升级';


-- -----------------------------------------------------
-- Table `upsite`.`addr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `upsite`.`addr` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '升级服务地域';


-- -----------------------------------------------------
-- Table `upsite`.`server`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `upsite`.`server` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `addr` INT UNSIGNED NOT NULL COMMENT '所属地域',
  `ipaddr` VARCHAR(39) ASCII NOT NULL COMMENT '虚拟机地址',
  `version` VARCHAR(20) NOT NULL DEFAULT '',
  `mask` VARCHAR(39) ASCII NOT NULL COMMENT '处理的网段',
  `online` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_server_1_idx` (`addr` ASC),
  UNIQUE INDEX `ipaddr_UNIQUE` (`ipaddr` ASC),
  CONSTRAINT `fk_server_1`
    FOREIGN KEY (`addr`)
    REFERENCES `upsite`.`addr` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = '升级服务';


-- -----------------------------------------------------
-- Table `upsite`.`v6`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `upsite`.`v6` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `belong` INT UNSIGNED NULL,
  `server` INT UNSIGNED NOT NULL COMMENT '所属升级服务',
  `ipaddr` VARCHAR(39) ASCII NOT NULL,
  `flow` INT UNSIGNED NOT NULL COMMENT '带宽',
  `site` INT UNSIGNED NOT NULL COMMENT '限制绑定的网站数',
  `desc` VARCHAR(45) NULL COMMENT '备注',
  `time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `addr_UNIQUE` (`ipaddr` ASC),
  INDEX `fk_v6_1_idx` (`belong` ASC),
  INDEX `fk_v6_2_idx` (`server` ASC),
  CONSTRAINT `fk_v6_1`
    FOREIGN KEY (`belong`)
    REFERENCES `upsite`.`user` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_v6_2`
    FOREIGN KEY (`server`)
    REFERENCES `upsite`.`server` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `upsite`.`loginLog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `upsite`.`loginLog` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ip` VARCHAR(39) ASCII NOT NULL,
  `user` VARCHAR(20) NOT NULL,
  `pwd` VARCHAR(20) NOT NULL,
  `time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `upsite`.`v6site`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `upsite`.`v6site` (
  `vid` INT UNSIGNED NOT NULL,
  `sid` INT UNSIGNED NOT NULL,
  `time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`vid`, `sid`),
  INDEX `fk_v6site_2_idx` (`sid` ASC),
  CONSTRAINT `fk_v6site_1`
    FOREIGN KEY (`vid`)
    REFERENCES `upsite`.`v6` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_v6site_2`
    FOREIGN KEY (`sid`)
    REFERENCES `upsite`.`site` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `upsite`.`downLog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `upsite`.`downLog` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `server` INT UNSIGNED NOT NULL,
  `opt` TINYTEXT NOT NULL,
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '0待处理 1成功 2失败',
  `downTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `replyTime` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_downLog_1_idx` (`server` ASC),
  CONSTRAINT `fk_downLog_1`
    FOREIGN KEY (`server`)
    REFERENCES `upsite`.`server` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = '下发命令记录';

CREATE USER 'upsite' IDENTIFIED BY 'Hello.123';

GRANT ALL ON `upsite`.* TO 'upsite';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `upsite`.`admin`
-- -----------------------------------------------------
START TRANSACTION;
USE `upsite`;
INSERT INTO `upsite`.`admin` (`id`, `name`, `nickName`, `pwd`, `token`, `time`) VALUES (1, 'admin', '超级管理员', 'e4250fbbca794ef4dc240dd53e3e8fd3', '', '2018-07-21 14:59:49');
INSERT INTO `upsite`.`addr` (`name`) VALUES ( '本地');

COMMIT;

